version: '3' ##VERSION DE DOCKER
services:     #SE DEFINEN LOS SERVICIOS A UTILIZAR

  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment: ### VARIABLES DE ENTORNO
      POSTGRES_DB: ms_products
      POSTGRES_USER: java
      POSTGRES_PASSWORD: java123
    ports:
      - 5431:5432  # MAPEO DE PUERTO
    expose:
      - 5432  # EXPONE PUERTO
    command: -p 5432  # ASEGURA QUE SE USE ESE PUERTO

  db-orders:
    container_name: db-orders
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_orders
      POSTGRES_USER: java
      POSTGRES_PASSWORD: java123
    ports:
      - 3000:5432  # MAPEO DE PUERTO
    expose:
      - 5432  # EXPONE PUERTO
    command: -p 5432  # ASEGURA QUE SE USE ESE PUERTO
  db-deliveries:
    container_name: db-deliveries
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_deliveries
      POSTGRES_USER: java
      POSTGRES_PASSWORD: java123
    ports:
      - 6000:6000  # MAPEA PUERTO
    expose:
      - 6000
    command: -p 6000
