
openapi: 3.0.1
info:
  version: "1.0.0"
  title: Deliveries API
  description: API para la gestión de envios
servers:
  - url: http://localhost:8085
    description: Local server
paths:
  /api/orders:
    get:
      summary: Obtener envios
      description: Retorna una lista de envios
      responses:
        '200':
          description: Lista de envios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Delivery'
    post:
      summary: Crear nueva envio
      description: Crea una nueva envio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Delivery'
      responses:
        '201':
          description: Envio creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                type: array
                items:
  /api/orders/{id}:
    put:
      summary: Actualizar envio
      description: Actualiza una envio existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Delivery'
      responses:
        '200':
          description: Envio actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '404':
          description: Envio no encontrada
          content:
            application/json:
              schema:
                type: string
    delete:
      summary: Eliminar envio
      description: Elimina una envio existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Envio eliminada exitosamente
        '404':
          description: Envio no encontrada
    get:
      summary: Comprobar existencia de envio
      description: Verifica si una envio existe por su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Envio encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '404':
          description: Envio no encontrada

components:
  schemas:
    Delivery:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        productIds:
          type: array
          items:
            type: integer
            format: int64
          example: [1, 2, 3]
        customerName:
          type: string
          example: "Nombre del cliente"
        home:
          type: string
          example: "Domicilio"
        totalAmount:
          type: number
          format: double
          example: 150.75
        status:
          type: boolean
          example: true
